"""
Emit the paper's result tables straight from the recorded metrics.

paper/main.tex \\input{}s these files, so a number can only appear in the paper
if it appears in results/metrics/. The previous version of this paper hand-typed
its tables and drifted from the experiments that produced them.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Dict, List

logger = logging.getLogger(__name__)

REPO = Path(__file__).resolve().parent.parent
METRICS = REPO / "results" / "metrics"
TABLES = REPO / "paper" / "tables"

MODEL_ORDER = [
    "TF-IDF + LinearSVM",
    "TF-IDF + LogReg",
    "Behavior + LogReg",
    "Behavior + RandomForest",
    "Relation GNN",
    "Text-only MLP",
    "Behavior-only MLP",
    "ReviewGuard (Fusion)",
]
# Models evaluated outside the main run; they appear in the protocol table only.
PROTOCOL_ONLY = {"Relation GNN"}
REFERENCE = "ReviewGuard (Fusion)"


def _load(name: str) -> Dict:
    return json.loads((METRICS / name).read_text())


def _load_optional(name: str) -> Dict:
    path = METRICS / name
    return json.loads(path.read_text()) if path.exists() else {}


def _merge_gnn(prod: Dict, user: Dict) -> None:
    """Fold the GNN runs into the two protocol summaries, when present."""
    for scope, target in (("product", prod), ("user", user)):
        g = _load_optional(f"gnn_results_by_{scope}.json")
        if g and "Relation GNN" in g.get("summary", {}):
            target["summary"]["Relation GNN"] = g["summary"]["Relation GNN"]


def _ms(entry: Dict, key: str) -> str:
    return f"{entry[key]['mean']:.3f} $\\pm$ {entry[key]['std']:.3f}"


def _bold_best(rows: List[List[str]], col: int, values: List[float]) -> None:
    best = max(range(len(values)), key=lambda i: values[i])
    rows[best][col] = f"\\textbf{{{rows[best][col]}}}"


def table_main(prod: Dict) -> str:
    models = [m for m in MODEL_ORDER
              if m in prod["summary"] and m not in PROTOCOL_ONLY]
    keys = ["auc_roc", "average_precision", "macro_f1", "recall_fake"]
    rows = [[m.replace("&", "\\&")] + [_ms(prod["summary"][m], k) for k in keys]
            for m in models]
    for ci, k in enumerate(keys, start=1):
        _bold_best(rows, ci, [prod["summary"][m][k]["mean"] for m in models])

    body = "\n".join(" & ".join(r) + r" \\" for r in rows)
    return f"""% generated by src/make_tables.py -- do not edit
\\begin{{table*}}[t]
\\caption{{Five-fold cross-validated performance on YelpCHI under the
business-disjoint protocol (mean $\\pm$ s.d. across folds). Decision thresholds
for every model are tuned on a held-out validation slice to maximize Macro-F1.}}
\\label{{tab:results}}
\\centering
\\small
\\begin{{tabular}}{{lcccc}}
\\toprule
\\textbf{{Model}} & \\textbf{{AUC-ROC}} & \\textbf{{AP}} & \\textbf{{Macro-F1}} & \\textbf{{Rec(Fake)}} \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table*}}
"""


def table_protocol(prod: Dict, user: Dict) -> str:
    models = [m for m in MODEL_ORDER
              if m in prod["summary"] and m in user["summary"]]
    triples = [
        (m,
         user["summary"][m]["auc_roc"]["mean"],
         prod["summary"][m]["auc_roc"]["mean"])
        for m in models
    ]
    triples.sort(key=lambda t: t[1] - t[2])  # ascending gap
    rows = [f"{m} & {u:.3f} & {p:.3f} & {u - p:+.3f} \\\\"
            for m, u, p in triples]
    body = "\n".join(rows)
    return f"""% generated by src/make_tables.py -- do not edit
\\begin{{table}}[htbp]
\\caption{{Effect of the evaluation protocol on AUC-ROC. The reviewer-disjoint
split allows a business to appear in both training and test folds; the
business-disjoint split does not. The gap is the portion of apparent
performance attributable to memorizing which businesses were spam targets.
Rows are ordered by that gap.}}
\\label{{tab:protocol}}
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{@{{}}lccc@{{}}}}
\\toprule
\\textbf{{Model}} & \\textbf{{Rev.-disj.}} & \\textbf{{Bus.-disj.}} & \\textbf{{Gap}} \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def table_significance(prod: Dict) -> str:
    tests = prod["wilcoxon_vs_reference"]
    rows = []
    for m in MODEL_ORDER:
        if m == REFERENCE or m not in tests or m in PROTOCOL_ONLY:
            continue
        a, f = tests[m]["auc_roc"], tests[m]["macro_f1"]
        rows.append(
            f"{m} & {a['delta']:+.3f} & {a['p_value']:.4f} "
            f"& {f['delta']:+.3f} & {f['p_value']:.4f} \\\\"
        )
    body = "\n".join(rows)
    n_folds = len(prod["summary"][REFERENCE]["auc_roc"]["folds"])
    return f"""% generated by src/make_tables.py -- do not edit
\\begin{{table}}[htbp]
\\caption{{Wilcoxon signed-rank tests of ReviewGuard against each baseline over
the {n_folds} business-disjoint folds. $\\Delta$ is ReviewGuard's mean per-fold
advantage. At $n = {n_folds}$ the smallest attainable two-sided $p$-value is
0.0625, so 0.0625 denotes a clean sweep of all {n_folds} folds.}}
\\label{{tab:significance}}
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{@{{}}lcccc@{{}}}}
\\toprule
& \\multicolumn{{2}}{{c}}{{\\textbf{{AUC-ROC}}}} & \\multicolumn{{2}}{{c}}{{\\textbf{{Macro-F1}}}} \\\\
\\cmidrule(lr){{2-3}} \\cmidrule(lr){{4-5}}
\\textbf{{Baseline}} & $\\boldsymbol{{\\Delta}}$ & $p$ & $\\boldsymbol{{\\Delta}}$ & $p$ \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def table_integrity(audit: Dict) -> str:
    ts = audit["timestamps"]
    biz = audit.get("business_identity", {})
    nat = max(abs(v) for k, v in audit["supplied_behavior_file"].items()
              if k.endswith("_vs_natural"))
    lab = max(abs(v) for k, v in audit["supplied_behavior_file"].items()
              if k.endswith("_vs_label"))
    rows = [
        ("\\texttt{date} column", "AUC from timestamp alone",
         f"{ts['auc_from_timestamp_alone']:.3f}"),
        ("", "Monthly fake-rate range",
         f"{ts['monthly_fake_rate_min']:.3f}--{ts['monthly_fake_rate_max']:.3f}"),
        ("", "Distinct seconds values", str(ts["distinct_seconds_values"])),
        ("\\texttt{behavioral\\_}", "Max $|r|$ vs.\\ own definition", f"{nat:.3f}"),
        ("\\texttt{features.csv}", "Max $|r|$ vs.\\ label", f"{lab:.3f}"),
    ]
    if biz:
        rows += [
            ("Business identity", "Businesses with no fakes",
             f"{biz['products_with_zero_fakes']}/{biz['n_products']}"),
            ("", "AUC from business fake rate",
             f"{biz['auc_of_product_fake_rate_as_predictor']:.3f}"),
        ]
    body = "\n".join(f"{a} & {b} & {c} \\\\" for a, b, c in rows)
    return f"""% generated by src/make_tables.py -- do not edit
\\begin{{table}}[htbp]
\\caption{{Data integrity audit. The first two blocks describe inputs excluded
from the study; the third describes a property of YelpCHI itself that dictates
the evaluation protocol.}}
\\label{{tab:integrity}}
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{@{{}}llr@{{}}}}
\\toprule
\\textbf{{Source}} & \\textbf{{Diagnostic}} & \\textbf{{Value}} \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def table_regime(prod_ind: Dict, prod_tra: Dict) -> str:
    """Business-disjoint protocol under both feature regimes."""
    models = [m for m in MODEL_ORDER
              if m in prod_ind["summary"] and m in prod_tra["summary"]
              and m not in PROTOCOL_ONLY]
    rows = []
    for m in models:
        i = prod_ind["summary"][m]["auc_roc"]["mean"]
        t = prod_tra["summary"][m]["auc_roc"]["mean"]
        rows.append(f"{m} & {i:.3f} & {t:.3f} & {t - i:+.3f} \\\\")
    body = "\n".join(rows)
    return f"""% generated by src/make_tables.py -- do not edit
\\begin{{table}}[htbp]
\\caption{{AUC-ROC under the business-disjoint split in both feature regimes.
The split, models and tuning are identical; only the source of the reviewer and
business aggregates differs, and neither regime uses a label. The gain is the
cost of the strict regime -- information withheld rather than leakage removed.}}
\\label{{tab:regime}}
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{@{{}}lccc@{{}}}}
\\toprule
\\textbf{{Model}} & \\textbf{{Inductive}} & \\textbf{{Transductive}} & \\textbf{{Gain}} \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def table_graph(gnn_prod: Dict, gnn_user: Dict,
                deg_prod: Dict, deg_user: Dict) -> str:
    """Graph models and the degree control, under both splits."""
    def row(label: str, u: float, pr: float) -> str:
        gap = "---" if u is None or pr is None else f"{u - pr:+.3f}"
        us = "---" if u is None else f"{u:.3f}"
        ps = "---" if pr is None else f"{pr:.3f}"
        return f"{label} & {us} & {ps} & {gap} \\\\"

    rows = []
    if gnn_prod:
        rows.append(row("Relation GNN",
                        _auc_or(gnn_user, "Relation GNN"),
                        _auc_or(gnn_prod, "Relation GNN")))
    for label, key in (("Behavior MLP", "Behavior MLP"),
                       ("\\quad $+$ graph degree", "Behavior MLP + graph degree"),
                       ("R-S-R degree alone", "R-S-R degree alone")):
        rows.append(row(label, _auc_or(deg_user, key), _auc_or(deg_prod, key)))
    body = "\n".join(rows)
    return f"""% generated by src/make_tables.py -- do not edit
\\begin{{table}}[htbp]
\\caption{{Graph models and the control that isolates what their edges carry.
The control is the behavior MLP given only the two full-graph degrees. Note the
last row: the split changes what a degree is worth by 0.001, because a degree is
read off the whole graph either way. The split removes business information from
the feature matrix, not from the topology.}}
\\label{{tab:graph}}
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{@{{}}lccc@{{}}}}
\\toprule
\\textbf{{Model}} & \\textbf{{Rev.-disj.}} & \\textbf{{Bus.-disj.}} & \\textbf{{Gap}} \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def _auc_or(d: Dict, model: str):
    if not d or model not in d.get("summary", {}):
        return None
    return d["summary"][model]["auc_roc"]["mean"]


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    prod = _load("real_yelpchi_results_by_product.json")
    user = _load("real_yelpchi_results_by_user.json")
    audit = _load("data_integrity_audit.json")
    _merge_gnn(prod, user)
    prod_tra = _load_optional("real_yelpchi_results_by_product_transductive.json")
    gnn_prod = _load_optional("gnn_results_by_product.json")
    gnn_user = _load_optional("gnn_results_by_user.json")
    deg_prod = _load_optional("degree_control_by_product.json")
    deg_user = _load_optional("degree_control_by_user.json")

    TABLES.mkdir(parents=True, exist_ok=True)
    for stem, content in [
        ("results_main", table_main(prod)),
        ("protocol_comparison", table_protocol(prod, user)),
        ("significance", table_significance(prod)),
        ("integrity", table_integrity(audit)),
    ] + (
        [("regime_comparison", table_regime(prod, prod_tra))] if prod_tra else []
    ) + (
        [("graph_comparison",
          table_graph(gnn_prod, gnn_user, deg_prod, deg_user))]
        if (gnn_prod or deg_prod) else []
    ):
        (TABLES / f"{stem}.tex").write_text(content)
        logger.info("wrote paper/tables/%s.tex", stem)


if __name__ == "__main__":
    main()
